baseurl: https://athanismyson.com/
languageCode: en-us
theme: stack
paginate: 5
title: Athan is my Son

# Change it to your Disqus shortname before using
# disqusShortname: 

# GA Tracking ID
# googleAnalytics:

# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, es, de, nl, it
DefaultContentLanguage: id

# Ignore error on vimeo
ignoreErrors: error-remote-getjson

#enable emoji
enableEmoji: true

permalinks:
    post: /p/:slug/
    page: /:slug/

params:
    mainSections:
        - post
    featuredImageField: image
    rssFullContent: true
    favicon: /favicon.ico

    footer:
        since: 2021
        customText: Because Athan is my Son of course.

    dateFormat:
        published: 02 Jan 2006
        lastUpdated: 02 Jan 2006 15:04 UTC+07.00

    sidebar:
        emoji: 👨‍🏫
        subtitle: Just another diary of cool-looking-wannabe father.
        avatar:
            enabled: true
            local: true
            src: img/avatar.png

    article:
        math: false
        toc: true
        readingTime: true
        license:
            enabled: true
            default: Licensed under CC BY-NC-SA 4.0

    comments:
        enabled: false
        provider: disqus

        # disqusjs:
        #    shortname:
        #    apiUrl:
        #    apiKey:
        #    admin:
        #    adminLabel:

    widgets:
        enabled:
            - search
            - archives
            - tag-cloud

        archives:
            limit: 5

        tagCloud:
            limit: 10

   
    defaultImage:
        opengraph:
            enabled: false
            local: false
            src:

    colorScheme:
        # Display toggle
        toggle: false

        # Available values: auto, light, dark
        default: light

    imageProcessing:
        cover:
            enabled: true
        content:
            enabled: true

### Custom menu
### See https://docs.stack.jimmycai.com/configuration/custom-menu.html
### To remove about, archive and search page menu item, remove `menu` field from their FrontMatter
menu:
    main:
        - identifier: home
          name: Home
          url: /
          weight: -100
          pre: home
          params:
              ### For demonstration purpose, the home link will be open in a new tab
              newTab: false

related:
    includeNewer: true
    threshold: 60
    toLower: false
    indices:
        - name: tags
          weight: 100

        - name: categories
          weight: 200

markup:
    tableOfContents:
        endLevel: 4
        ordered: true
        startLevel: 2
    highlight:
        noClasses: false
